events.api.event.join:
  path: /event/{eventId}/join/{userId}
  controller: App\Controller\JoinEventController::join
  methods: [POST]

events.api.event.leave:
  path: /event/{eventId}/leave/{userId}
  controller: App\Controller\JoinEventController::leave
  methods: [POST]